# Generated by Django 6.0.3 on 2026-03-15 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_mapping', models.BooleanField(default=False)),
                ('product_child_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('vendor_parent_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
            options={
                'unique_together': {('vendor_parent_fk', 'product_child_fk')},
            },
        ),
    ]
